import { build as esbuild } from "esbuild";
import { build as viteBuild } from "vite";
import { rm, readFile, mkdir } from "fs/promises";
import path from "path";

// server deps to bundle to reduce openat(2) syscalls
// which helps cold start times
const allowlist = [
  "@google/generative-ai",
  "axios",
  "connect-pg-simple",
  "cors",
  "date-fns",
  "drizzle-orm",
  "drizzle-zod",
  "express",
  "express-rate-limit",
  "express-session",
  "jsonwebtoken",
  "memorystore",
  "multer",
  "nanoid",
  "nodemailer",
  "openai",
  "passport",
  "passport-local",
  "pg",
  "stripe",
  "uuid",
  "ws",
  "xlsx",
  "zod",
  "zod-validation-error",
];

const sharedEsbuildOptions = {
  platform: "node" as const,
  bundle: true,
  minify: true,
  logLevel: "info" as const,
  define: {
    "process.env.NODE_ENV": '"production"',
  },
  alias: {
    "@shared": path.resolve("shared"),
  },
};

async function buildAll() {
  await rm("dist", { recursive: true, force: true });
  await rm("api", { recursive: true, force: true });

  console.log("building client...");
  await viteBuild();

  console.log("building server...");
  const pkg = JSON.parse(await readFile("package.json", "utf-8"));
  const allDeps = [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.devDependencies || {}),
  ];
  const externals = allDeps.filter((dep) => !allowlist.includes(dep));

  // Standard server build (for local / non-Vercel)
  await esbuild({
    ...sharedEsbuildOptions,
    entryPoints: ["server/index.ts"],
    format: "cjs",
    outfile: "dist/index.cjs",
    external: externals,
  });

  // Vercel serverless function build — bundle everything, no externals
  console.log("building Vercel serverless function...");
  await mkdir("api", { recursive: true });
  await esbuild({
    ...sharedEsbuildOptions,
    entryPoints: ["server/vercel.ts"],
    format: "esm",
    outfile: "api/index.mjs",
    // Bundle all dependencies for serverless (no externals)
    external: [],
    banner: {
      js: '// Vercel serverless function — auto-generated by build script',
    },
  });
}

buildAll().catch((err) => {
  console.error(err);
  process.exit(1);
});
